url = "interactions.ics.unisg.ch"
user = "admin"
password = "inthrustwetrust"
database_name = "sensor_net"
port = 8086
sparql_endpoint = "https://graphdb.interactions.ics.unisg.ch/repositories/explanantion-cd"
sparql_username = "sanjivjha"
sparql_password = "Junglebook2$C"
contextApiUrl = "http://127.0.0.1:5000/context?sensorname="